#!/bin/sh

bspc monitor -d 0001 0010 0011 0100 0101

desktop_config()
{
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}

desktop_config border_width 2
desktop_config window_gap 40
bspc config split_ratio 0.5
#bspc config top_padding 18
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer false
bspc config click_to_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#a6a6a6"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#ffffff"

#panel &
